import os

# files
RAW_STATS_FILE_NAME = 'raw_stats_test.csv'
RAW_STATS_FILE_PATH = os.path.join(os.path.dirname(__file__), '..', 'resources', RAW_STATS_FILE_NAME)

# columns
COLUMN_DATE = 'Date'
COLUMN_PITCHER = 'Pitcher'
COLUMN_BATTER = 'Batter'
COLUMN_OUTCOME = 'Outcome'
COLUMN_FIELDERS = 'Fielders'

# ON BASE outcomes
OUTCOME_SINGLE = '1B'
OUTCOME_DOUBLE = '2B'
OUTCOME_TRIPLE = '3B'
OUTCOME_OUTSIDE_PARK_HOMERUN = 'HR'
OUTCOME_INSIDE_PARK_HOMERUN = '4B'
OUTCOME_WALK = 'BB'
OUTCOME_INTENTIONAL_WALK = 'IBB'
OUTCOME_HIT_BY_PITCH = 'HBP'

# OUT outcomes
OUTCOME_STRIKEOUT = 'K'
OUTCOME_GROUNDOUT_TO_FIRST = 'G1'
OUTCOME_GROUNDOUT_TO_SECOND = 'G2'
OUTCOME_GROUNDOUT_TO_THIRD = 'G3'
OUTCOME_GROUNDOUT_TO_HOME = 'G4'
OUTCOME_FLYOUT = 'F'
OUTCOME_DOUBLE_PLAY = 'DP'
OUTCOME_TRIPLE_PLAY = 'TP'

# arrays for stat checking
OUTCOMES_HIT = [OUTCOME_SINGLE, OUTCOME_DOUBLE, OUTCOME_TRIPLE, OUTCOME_OUTSIDE_PARK_HOMERUN, OUTCOME_INSIDE_PARK_HOMERUN]
OUTCOMES_ON_BASE = OUTCOMES_HIT + [OUTCOME_WALK, OUTCOME_INTENTIONAL_WALK, OUTCOME_HIT_BY_PITCH]
OUTCOMES_OUT = [OUTCOME_STRIKEOUT, OUTCOME_GROUNDOUT_TO_FIRST, OUTCOME_GROUNDOUT_TO_SECOND, OUTCOME_GROUNDOUT_TO_THIRD, OUTCOME_GROUNDOUT_TO_HOME, OUTCOME_FLYOUT, OUTCOME_DOUBLE_PLAY, OUTCOME_TRIPLE_PLAY]
OUTCOMES_AT_BAT = OUTCOMES_HIT + OUTCOMES_OUT
OUTCOMES_PLATE_APPEARANCE = OUTCOMES_ON_BASE + OUTCOMES_OUT
