import os

RAW_STATS_FILE_NAME = 'raw_stats_test.csv'
RAW_STATS_FILE_PATH = os.path.join(os.path.dirname(__file__), '..', 'resources', RAW_STATS_FILE_NAME)

OUTCOME_SINGLE = '1B'
OUTCOME_DOUBLE = '2B'
OUTCOME_TRIPLE = '3B'
OUTCOME_OUTSIDE_PARK_HOMERUN = 'HR'
OUTCOME_INSIDE_PARK_HOMERUN = '4B'

OUTCOME_STRIKEOUT = 'K'
OUTCOME_WALK = 'BB'
OUTCOME_INTENTIONAL_WALK = 'IBB'
OUTCOME_HIT_BY_PITCH = 'HBP'

OUTCOME_GROUNDOUT_TO_FIRST = 'G1'
OUTCOME_GROUNDOUT_TO_SECOND = 'G2'
OUTCOME_GROUNDOUT_TO_THIRD = 'G3'
OUTCOME_GROUNDOUT_TO_HOME = 'G4'
OUTCOME_FLYOUT = 'F'

OUTCOME_DOUBLE_PLAY = 'DP'
OUTCOME_TRIPLE_PLAY = 'TP'